server:
  port: 8081
spring:
  application:
    # Ӧ�����ƣ�Ҳ�ǵ�ǰӦ����ע�����ĵ�serviceId
    name: nch-health-consulting
  multipart:
    maxFileSize: 100MB
    maxRequestSize: 100MB
    filePath: d:/uploads/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  # ���ݿ�����
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.5.172:3306/zufang?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 1234.Aaaa
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect